// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20191101224450_TestData")]
    partial class TestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsFixed");

                    b.Property<string>("Name");

                    b.Property<string>("Taxonomy");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Breed = "Golden Retriever",
                            Gender = "Male",
                            IsFixed = true,
                            Name = "Bob",
                            Taxonomy = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            Breed = "Labrador",
                            Gender = "Male",
                            IsFixed = false,
                            Name = "Fred",
                            Taxonomy = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Breed = "Tuxedo",
                            Gender = "Female",
                            IsFixed = false,
                            Name = "Sally",
                            Taxonomy = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 11,
                            Breed = "Poodle",
                            Gender = "Male",
                            IsFixed = true,
                            Name = "Oliver",
                            Taxonomy = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 5,
                            Breed = "Pomeranian",
                            Gender = "Female",
                            IsFixed = true,
                            Name = "Lola",
                            Taxonomy = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 2,
                            Breed = "Tuxedo",
                            Gender = "Male",
                            IsFixed = true,
                            Name = "Bruce",
                            Taxonomy = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 200,
                            Breed = "Humpback",
                            Gender = "Male",
                            IsFixed = false,
                            Name = "Jay",
                            Taxonomy = "Whale"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 30,
                            Breed = "Orangutan",
                            Gender = "Male",
                            IsFixed = false,
                            Name = "Chad",
                            Taxonomy = "Great Ape"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 7,
                            Breed = "Weasel",
                            Gender = "Male",
                            IsFixed = true,
                            Name = "Rich",
                            Taxonomy = "Mustelidae"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 8,
                            Breed = "Bullfrog",
                            Gender = "Male",
                            IsFixed = false,
                            Name = "Xyronic",
                            Taxonomy = "Frog"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 31,
                            Breed = "Elephant Seal",
                            Gender = "Male",
                            IsFixed = false,
                            Name = "Conway",
                            Taxonomy = "Seal"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 28,
                            Breed = "Silverback",
                            Gender = "Male",
                            IsFixed = false,
                            Name = "Derrick",
                            Taxonomy = "Gorilla"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 25,
                            Breed = "Pangolin",
                            Gender = "Male",
                            IsFixed = true,
                            Name = "Jon",
                            Taxonomy = "Manidae"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
